# Generated by Django 4.1 on 2022-08-22 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="update date"
                    ),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="deleted")),
                ("name", models.CharField(max_length=150, verbose_name="Name")),
                (
                    "types",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        default="public",
                        max_length=7,
                    ),
                ),
                ("date", models.DateField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="update date"
                    ),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="deleted")),
                ("name", models.CharField(max_length=150, verbose_name="Name")),
                ("capacity", models.IntegerField(verbose_name="Capacity")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Through_Room_User_busines",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="update date"
                    ),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="deleted")),
                (
                    "obj_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Through_Room_User_busines",
                        to="rentings.room",
                        verbose_name="Event",
                    ),
                ),
                (
                    "obj_user_busines",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Through_Room_User_busines",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User_busines",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Through_Event_User_customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="creation date"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="update date"
                    ),
                ),
                ("deleted", models.BooleanField(default=False, verbose_name="deleted")),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "obj_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Through_Event_User_customer",
                        to="rentings.event",
                        verbose_name="Event",
                    ),
                ),
                (
                    "obj_user_customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Through_Event_User_customer",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User_customer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="room",
            name="user",
            field=models.ManyToManyField(
                blank=True,
                through="rentings.Through_Room_User_busines",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="obj_room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="Events",
                to="rentings.room",
                verbose_name="Rooms",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="user",
            field=models.ManyToManyField(
                blank=True,
                through="rentings.Through_Event_User_customer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
