# Generated by Django 4.1 on 2022-08-23 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rentings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="through_event_user_customer",
            name="obj_user_customer",
            field=models.ForeignKey(
                limit_choices_to={"groups.name": "Customer"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Through_Event_User_customer",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User_customer",
            ),
        ),
        migrations.AddConstraint(
            model_name="through_event_user_customer",
            constraint=models.UniqueConstraint(
                fields=("obj_user_customer", "obj_event", "active"),
                name="unique__obj_user_customer__obj_event__active",
            ),
        ),
    ]
