# Generated by Django 4.1 on 2022-08-23 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rentings", "0003_remove_room_user_event_obj_user_busines_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="obj_user_busines",
            field=models.ForeignKey(
                limit_choices_to={"groups": 2},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Event",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User_busines",
            ),
        ),
    ]
