# Generated by Django 4.1 on 2022-08-23 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rentings", "0004_alter_event_obj_user_busines"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="obj_user_busines",
            field=models.ForeignKey(
                limit_choices_to={"groups": 2},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Room",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User_busines",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="obj_user_busines",
            field=models.ForeignKey(
                limit_choices_to={"groups": 2},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Event",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User_busines",
            ),
        ),
    ]
