# Generated by Django 4.1 on 2022-08-23 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rentings", "0005_room_obj_user_busines_alter_event_obj_user_busines"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="obj_user_busines",
            field=models.ForeignKey(
                limit_choices_to={"groups": 2},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User_busines",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="obj_user_busines",
            field=models.ForeignKey(
                limit_choices_to={"groups": 2},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Rooms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User_busines",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                fields=("obj_room", "date"), name="unique__obj_room__date"
            ),
        ),
    ]
